version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
       - 80:80
    restart: unless-stopped
    depends_on:
       - api
    networks:
       - nginx-network
  api:
    image: psp29/app-api
    build:
      context: './assignment1DotnetSQLite'
      dockerfile: Dockerfile
    expose:
       - 5000
    restart: unless-stopped
    networks:
       - nginx-network
networks:
  nginx-network:
    driver: bridge
